### PR TITLE
DB: Un'goro spawns

### PR DESCRIPTION
**Pull request by thomas33**
All Un'goro spawns (creature and gameobject)

#555

### CODE REVIEW

**Comment by SkyFire** [comment]
I will check theses sometime this week. Unless AriDEV beats me to it.

**Comment by ProjectcoreDevs** [comment]
tested its good for me !

**Comment by AriDEV** [comment]
@ProjectcoreDevs any guid gaps? are there no missing templates ? do we have all the template data?

**Comment by Rushor** [comment]
use the waypointcreator from malcrom :P

**Comment by Rushor** [comment]
why closing - project SkyFire.548 dead?

**Comment by SkyFire** [comment]
It's not dead.

**Comment by Rushor** [comment]
well @thomas33 could at least explain why he closed all his prs in SkyFire.548

**Pull request closed without merging**
