### PR TITLE
Update Trade system opcode/structure/updatefield

### PR DESCRIPTION
**Pull request by ProjectcoreDevs**
Tested in game, work perfecly ! :)

### CODE REVIEW

**Comment by ProjectcoreDevs** [comment]
i work on movements opcode, i pull in 1 hour i think, i update all opcodes spline, move in smsg for now

**Comment by AriDEV** [comment]
jump on irc wanna talk to u

**Comment by ProjectcoreDevs** [comment]
wich channel? skyfire?

**Comment by AriDEV** [comment]
yes

**Pull request merged**
