### PR TITLE
Player/Ressurect: fixed waterwalking after revive. Fixes #653

### LINKED ISSUE #653: Water walking after die
SkyFire 5.x.x rev. 07ebba257b75 2015-09-17 12:05:47 +0200 (master branch) (Unix, Release)

if i die underwater, when i came back to life i can walk on water

### PR DESCRIPTION
**Pull request by Arcidev**

### CODE REVIEW

**Comment by thomas33** [comment]
thanks @IvanVojtko .  a0acd9b

**Comment by Arcidev** [comment]
if you say so... sniffs are better source

**Comment by cavaclub** [comment]
thank you

**Comment by SkyFire** [comment]
And the TC commit police are active today.

**Pull request merged**
