### PR TITLE
Fixxed SpellEffect.dbc - struct

### PR DESCRIPTION
**Pull request by Shoxxo**

### CODE REVIEW

**Comment by Shoxxo** [comment]
Okay, now we wait on Travis and after that we can check if it works, i need go in my bed it was a simple think i do

**Comment by soulfrost** [comment]
LoadDBC(availableDbcLocales, bad_dbc_files, sSpellEffectStore,            dbcPath,"SpellEffect.dbc"/*, &CustomSpellEffectEntryfmt, &CustomSpellEffectEntryIndex*/);//15595

cos it's disabled atm ( not updated to mop )...
u really dont understand what are u doing?

**Comment by Shoxxo** [comment]
Let me do what i do okay. if you can do it better, than make your own pull request, i hear only mimimimimi

**Comment by soulfrost** [comment]
i dont have any time to work with mop, cos i'm working just on 7.0.3 atm

**Comment by Shoxxo** [comment]
Fucking 7.0.3 i hate it and i never spend time on a server core what has no public live server from blizzard... thats fact, you will do a core with many of fucking bugs. complete first one core to stable and playable and than i start next think

**Comment by AriDEV** [comment]
is there any sql update aswell for the change of the structure ?

**Comment by soulfrost** [comment]
offtop
@Shoxxo server there i'm working have >= 14 000 players online every day, u think we have "many of fucking bugs" ? rofl

**Comment by alterego21** [comment]
Who gives a fuck about your illegal  private server.

**Comment by soulfrost** [comment]
who cares about ur fucking project whre's no devs and just some PRs which made by peoples who dont understand what are they doing; all that they can do: CTRL + C -> CTRL + V ( as well they cant test they changes - fe this pr, changes done but server'll not start with this changes )

**Comment by Shoxxo** [comment]
@AriDEV IDK, i checked all in my NP repo and i do not find a change, i will start a testserver and see if error or not

**Comment by AriDEV** [comment]
CustomSpellEffectEntryfmt is for loading serverside spells that are not in client database its disabled for now. but if u change the structure and enable it your server wont start without the correct structure in database.

**Comment by Arcidev** [comment]
@soulfrost you obviosly cares as you're still commenting here... FYI Pandashan use to have 10k+ population a day also when they've been first and the only ones who had pandaria and there were plenty of bugs (population is not related only to functionality)

**Comment by Shoxxo** [comment]
Thats the reason why no peoples will help here with the time, i UPDATED it and my Stream is Online, my Server works with exactly THIS changes but okay i will no longer spend time in this project.

**Comment by AriDEV** [comment]
@Shoxxo the code that @soulfrost posted uncomment the commented part to enable spells loading from database and test it then.

**Comment by Zerixx** [comment]
> i dont have any time to work with mop, cos i'm working just on 7.0.3 atm

Doubt it.

**Comment by soulfrost** [comment]
@Zerixx come to http://epicwow.com/ ;)

**Comment by SkyFire** [comment]
@soulfrost This is not recruiting for your illegal private server

**Comment by soulfrost** [comment]
ya man, it's just answer - offtop

**Pull request closed without merging**
