### PR TITLE
Server/PacketIO: Added SMSG_ACTIVATE_TAXI_REPLY, SMSG_SEND_UNLEARN_SPELLS, SMSG_THREAT_REMOVE opcodes and updated SMSG_THREAT_REMOVE packet structure

### PR DESCRIPTION
**Pull request by Goatform**

### CODE REVIEW

**Comment by Goatform** [comment]
SMSG_ACTIVATE_TAXI_REPLY & SMSG_SEND_UNLEARN_SPELLS are same as on my core so I just updated SMSG_THREAT_REMOVE packet structure.

**Comment by ProjectcoreDevs** [comment]
SMSG_ACTIVATE_TAXI_REPLY = sub_6EC092 and for SMSG_SEND_UNLEARN_SPELLS =  sub_C6F114 same structure?

**Comment by Goatform** [comment]
Yeah, at least for me.

**Comment by Goatform** [comment]
Ohh damn I implemented this feature in my core, I forgot that skyfire doesn't have it.

**Comment by ProjectcoreDevs** [comment]
SMSG_ACTIVATE_TAXI_REPLY = 
    data.WriteBits(reply, 4);

**Comment by AriDEV** [comment]
Well Feel Free to update bytebuffer for it :) just name it not mask but WriteGuidStream and WriteGuidSeqStream dont forget to update the bytebuffer for CMSGs aswell :)

**Comment by Goatform** [comment]
So data.WriteGuidMask should be replaced with data.WriteBit and data.WriteGuidBytes with data.WriteByteSeq or ?

**Comment by AriDEV** [comment]
yes or u will need to update the bytebuffer :)

**Comment by ProjectcoreDevs** [comment]
yes

**Comment by ProjectcoreDevs** [comment]
too :p ari

**Comment by Goatform** [comment]
So for example it should be like this:

data.WriteBit(victimGUID, 0, 1, 5);

or I need to change code style too ?

**Comment by ProjectcoreDevs** [comment]
data.WriteBit(guid[0]);
    data.WriteBit(guid[1]);
    data.WriteBit(guid[5]);
    data.WriteBit(unitGuid[4]);
    data.WriteBit(unitGuid[0]);
    data.WriteBit(guid[4]);
    data.WriteBit(guid[6]);
    data.WriteBit(unitGuid[7]);
    data.WriteBit(unitGuid[6]);
    data.WriteBit(unitGuid[3]);
    data.WriteBit(guid[2]);
    data.WriteBit(unitGuid[1]);
    data.WriteBit(guid[3]);
    data.WriteBit(guid[7]);
    data.WriteBit(unitGuid[5]);
    data.WriteBit(unitGuid[2]);

    data.WriteByteSeq(unitGuid[3]);
    data.WriteByteSeq(unitGuid[0]);
    data.WriteByteSeq(unitGuid[2]);
    data.WriteByteSeq(guid[5]);
    data.WriteByteSeq(guid[4]);
    data.WriteByteSeq(guid[7]);
    data.WriteByteSeq(guid[3]);
    data.WriteByteSeq(guid[0]);
    data.WriteByteSeq(unitGuid[4]);
    data.WriteByteSeq(guid[1]);
    data.WriteByteSeq(unitGuid[1]);
    data.WriteByteSeq(guid[6]);
    data.WriteByteSeq(unitGuid[7]);
    data.WriteByteSeq(unitGuid[6]);
    data.WriteByteSeq(guid[2]);
    data.WriteByteSeq(unitGuid[5]);

**Comment by Goatform** [comment]
I changed guid/unitGuid to victimGUID & hostileGUID

**Comment by ProjectcoreDevs** [comment]
yes guid = victimGUID and unitGuid = hostileGUID

**Comment by Goatform** [comment]
It should be fixed now.

**Comment by ProjectcoreDevs** [comment]
good

**Comment by Goatform** [comment]
Yeah no compile errors now.

**Pull request merged**
