### PR TITLE
Delete unused files... My fail, forget to delete it...

### PR DESCRIPTION
**Pull request by Shoxxo**
Delete the folders Old_unused and Neuer Ordner, it was my fail... Not finished with that work...

### CODE REVIEW

**Comment by alterego21** [comment]
We can cherry pick. It will skip the unfinished work folder

**Comment by Shoxxo** [comment]
These files are changed with core changed ... fork it and close it thats all fast and clean... cherrypick... more work if unneeded... lol

**Comment by Zerixx** [comment]
So, what you've done, essentially, is taken WoWSource and copy and pasted it into this PR. You realize that you will have one hell of a time getting any of that to work, right?

**Comment by SkyFire** [comment]
@Zerixx Hey spear chucker. Come on IRC ;)

**Pull request closed without merging**
