### PR TITLE
Fix Movement Crash by modify movement speed

### PR DESCRIPTION
**Pull request by Shoxxo**
Fixxed the Movement modifier and server no longer crash if a player type .mod speed 10 or else ... :)

### CODE REVIEW

**Comment by SkyFire** [comment]
If your going to copy and paste this stuff. Please credit the authors. Else people will start whining about it.

**Comment by ChipLeo** [comment]
This is hack:: for SMSG_MOVE_UPDATE_APPLY_MOVEMENT_FORCE need 4 MSEExtraFloat ...

**Comment by akrom23** [comment]
@ChipLeo: SMSG_MOVE_UPDATE_APPLY_MOVEMENT_FORCE - when it applies?

**Comment by ChipLeo** [comment]
In Timeless Isle

**Comment by ChipLeo** [comment]
In Timeless Isle

**Comment by akrom23** [comment]
In Timeless Isle - some exact situations?

**Comment by soulfrost** [comment]
it's related to dynamic areaTriggers - there's no implentation of this on SF

**Comment by akrom23** [comment]
You mean Areatrigger entity?

**Comment by soulfrost** [comment]
i meen dynamic AreaTrigger system ( movement_force it's one of their options ) which's used for AreaTriggers created by spells

**Comment by akrom23** [comment]
Ok, I got it.

**Comment by Shoxxo** [comment]
let me do my work please, only if you mean it is not implentation so you are not able to wait... before i do 1000 pullrequests i will check it self than do request

**Pull request merged**
