### PR TITLE
Archaelogy and some fixxes! More comes if i have time for more 

### PR DESCRIPTION
**Pull request by Shoxxo**
Will be nice if i can see it in official repo :)

### CODE REVIEW

**Comment by SkyFire** [comment]
Looks like the build failed.

**Comment by SkyFire** [comment]
I am doing a check to see what failed.

**Comment by Shoxxo** [comment]
The DK Class has some failes... i think i will fix it if i found the time :) Today i will be look forward to fix others...

**Comment by Arcidev** [comment]
C++11 features have failed, like auto

**Comment by Shoxxo** [comment]
i push a fix in few minutes because cmake... updating all step by step to boost but it is not easy

**Comment by AriDEV** [comment]
'auto' is a C++11 only type specifier.

**Pull request merged**
