### PR TITLE
DB/World : Add access_requirement and instance_template For open instance MSV , TES , HOF , TOT

### PR DESCRIPTION
**Pull request by Nightprince**
Player after entering the portal , Core will be crash. this crash not for this sql , sql don't have any problem .
and difficulty 3 - 4 - 5 -6 for this : (DBC name : Difficulty.dbc )

http://www.yekta-upload.ir/uploads/14708314090991.jpg

### CODE REVIEW

**Comment by albablood** [comment]
i fix this myself, but inc npc's is'nt there them inc, for example:
68476 - Horridon isnt there in creature_template
it's my problem

**Comment by Nightprince** [comment]
you need to sniff from this instance . @albablood

**Comment by albablood** [comment]
ok. then what about toes?
check database
protectors of enless npc's isnt there @Nightprince

**Comment by Nightprince** [comment]
all instance is empty . need sniff . @albablood

**Pull request merged**
